version: '3.8'

services:
  postgres:
    image: postgres
    container_name: course_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: course_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      PGADMIN_SERVER_PORT: ${PGADMIN_SERVER_PORT}
      PGADMIN_SERVER_NAME: PostgreSQL
    ports:
      - "${PGADMIN_LISTEN_PORT}:8080"
    depends_on:
      - postgres
